### ISSUE TITLE
Triton Navigator failing to convert the tensorflow model into tensorflow-trt.

### ISSUE THREAD

**Issue by swapnil-lader** [triton-inference-server/model_navigator#14]
While trying conversion from the tf-savedmodel format to tf-trt format model-navigator throws error (Please provide a full dataset profile instead of max_batch_size.). We have given the dataset profile as mentioned below but it throws the same error. Model similar to retina face which have dynamix axes throws a similar error.

Multiple Dynamic Axes

Model - Retinaface face detection.

Model-Config 

target_formats: ["tf-trt"]

# model signature

inputs:

   input__0:

     name: data

     shape: [-1, -1, -1, 3]

     dtype: float32

outputs:

   output__0:

     name: face_rpn_bbox_pred_stride16

     shape: [-1, -1, -1, 8]

     dtype: float32

   output__1:

     name: face_rpn_bbox_pred_stride32

     shape: [-1, -1, -1, 8]

     dtype: float32

   output__2:

     name: face_rpn_bbox_pred_stride8

     shape: [-1, -1, -1, 8]

     dtype: float32

   output__3:

     name: face_rpn_landmark_pred_stride16

     shape: [-1, -1, -1, 20]

     dtype: float32

   output__0:

     name: face_rpn_landmark_pred_stride32

     shape: [-1, -1, -1, 20]

     dtype: float32

   output__0:

     name: face_rpn_landmark_pred_stride8

     shape: [-1, -1, -1, 20]

     dtype: float32

   output__0:

     name: tf.compat.v1.transpose_1

     shape: [-1, -1, -1, 4]

     dtype: float32

   output__0:

     name: tf.compat.v1.transpose_3

     shape: [-1, -1, -1, 4]

     dtype: float32

   output__0:

     name: tf.compat.v1.transpose_5

     shape: [-1, -1, -1, 4]

     dtype: float32

   output__0:

     name: face_rpn_bbox_pred_stride16

     shape: [-1, -1, -1, 8]

     dtype: float32

# comparator config

atol:

   output__0: 0.01

rtol:

   output__0: 0.1

# dataset profile

max_shapes:

   image__0: [-1, -1, -1, 3]

dtypes:

   image__0: float32

Model-Meta-Data

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['__saved_model_init_op']:

  The given SavedModel SignatureDef contains the following input(s):

  The given SavedModel SignatureDef contains the following output(s):

    outputs['__saved_model_init_op'] tensor_info:

        dtype: DT_INVALID

        shape: unknown_rank

        name: NoOp

  Method name is: 

signature_def['serving_default']:

  The given SavedModel SignatureDef contains the following input(s):

    inputs['data'] tensor_info:

        dtype: DT_FLOAT

        shape: (-1, -1, -1, 3)

        name: serving_default_data:0

  The given SavedModel SignatureDef contains the following output(s):

    outputs['face_rpn_bbox_pred_stride16'] tensor_info:

        dtype: DT_FLOAT

        shape: (-1, -1, -1, 8)

        name: StatefulPartitionedCall:0

    outputs['face_rpn_bbox_pred_stride32'] tensor_info:

        dtype: DT_FLOAT

        shape: (-1, -1, -1, 8)

        name: StatefulPartitionedCall:1

    outputs['face_rpn_bbox_pred_stride8'] tensor_info:

        dtype: DT_FLOAT

        shape: (-1, -1, -1, 8)

        name: StatefulPartitionedCall:2

    outputs['face_rpn_landmark_pred_stride16'] tensor_info:

        dtype: DT_FLOAT

        shape: (-1, -1, -1, 20)

        name: StatefulPartitionedCall:3

    outputs['face_rpn_landmark_pred_stride32'] tensor_info:

        dtype: DT_FLOAT

        shape: (-1, -1, -1, 20)

        name: StatefulPartitionedCall:4

    outputs['face_rpn_landmark_pred_stride8'] tensor_info:

        dtype: DT_FLOAT

        shape: (-1, -1, -1, 20)

        name: StatefulPartitionedCall:5

    outputs['tf.compat.v1.transpose_1'] tensor_info:

        dtype: DT_FLOAT

        shape: (-1, -1, -1, 4)

        name: StatefulPartitionedCall:6

    outputs['tf.compat.v1.transpose_3'] tensor_info:

        dtype: DT_FLOAT

        shape: (-1, -1, -1, 4)

        name: StatefulPartitionedCall:7

    outputs['tf.compat.v1.transpose_5'] tensor_info:

        dtype: DT_FLOAT

        shape: (-1, -1, -1, 4)

        name: StatefulPartitionedCall:8

  Method name is: tensorflow/serving/predict

Issues

/usr/local/lib/python3.8/dist-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.

  setattr(self, word, getattr(machar, word).flat[0])

/usr/local/lib/python3.8/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float32'> type is zero.

  return self._float_to_str(self.smallest_subnormal)

/usr/local/lib/python3.8/dist-packages/numpy/core/getlimits.py:499: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.

  setattr(self, word, getattr(machar, word).flat[0])

/usr/local/lib/python3.8/dist-packages/numpy/core/getlimits.py:89: UserWarning: The value of the smallest subnormal for <class 'numpy.float64'> type is zero.

  return self._float_to_str(self.smallest_subnormal)

Error: Cannot construct default dataset profile: too many dynamic axes in the model input data: [-1, -1, -1, 3]. Please provide a full dataset profile instead of max_batch_size.

Error: No results found for convert_model

**Comment by pziecina** [comment]
Hi @swapnil-lader,
your model has dynamic axes (batch_size + image size). Because of that, you were requested to provide a dataset profile which is required by the TensorRT optimizer. I see that you've provided `--max-shapes` with dynamic values:

```
max_shapes:
   image__0: [-1, -1, -1, 3]
```

You should provide batch_size and size of the image which according to your knowledge of model use, will commonly be passed to model input. Ex.

```
   --min-shapes image__0=1,32,32,3 \
   --opt-shapes image__0=16,224,224,3 \
   --max-shapes image__0=32,800,800,3
```

More information might be found [here](https://github.com/triton-inference-server/model_navigator/blob/main/docs/advanced/conversion.md#tensorrt-optimization-profiles).

Also as @ptarasiewiczNV mentioned in #13 - for conversion functionality, we're moving to [export API](https://github.com/triton-inference-server/model_navigator/blob/main/docs/export_from_source.md).

**Comment by swapnil-lader** [comment]
It worked, Thanks
