### ISSUE TITLE
[feature] add support for Host Policy in Triton Model Configurator

### ISSUE THREAD

**Issue by gnovack** [triton-inference-server/model_navigator#16]
When generating a model configuration using the `triton-config-model` command, it would great to allow users to assign Host Policies to specific instance groups as described in [Model Configuration - Host Policy](https://github.com/triton-inference-server/server/blob/a2240c56282e7928d430d7260c860875f0e698a1/docs/user_guide/model_configuration.md#host-policy)

**Comment by jkosek** [comment]
@gnovack thanks for suggestion. We are going to add support for this option.
