### ISSUE TITLE
Can't install Model Navigator

### ISSUE THREAD

**Issue by macrosend-fukumoto** [triton-inference-server/model_navigator#19]
## Issue
I want to install model navigator for pytorch but getting the error below.
![image](https://user-images.githubusercontent.com/98517563/221114179-6f8be933-e727-433f-af2b-b61e43d9b9c0.png)

## Environment
Ubuntu 18.04.6 LTS
Docker 20.10.13
CUDA Version: 11.7
NVIDIA-SMI 515.65.01
Driver Version: 515.65.01
GPU: Tesla T4

## Steps To reproduce
1. Create Docker File
```Dockerfile
FROM nvcr.io/nvidia/pytorch:22.10-py3
ENV DEBIAN_FRONTEND=noninteractive

# WAR for PEP660
RUN pip install --no-cache-dir --upgrade pip
RUN pip install janome fugashi ipadic
RUN pip install --extra-index-url https://pypi.ngc.nvidia.com .[pyt]


ENTRYPOINT []   
```
2. Build image
```shell
docker build -f model_nav.Dockerfile -t model-navigator .
```

**Comment by jkosek** [comment]
@macrosend-fukumoto you either need to copy the sources during build:
```
WORKDIR /opt/model-navigator
COPY . /opt/model-navigator

RUN pip install --extra-index-url https://pypi.ngc.nvidia.com .
```
or use the wheel available at GitHub
```
RUN pip install --extra-index-url https://pypi.ngc.nvidia.com https://github.com/triton-inference-server/model_navigator/releases/download/v0.4.1/triton_model_navigator-0.4.1-py3-none-any.whl
```
I suggest to use the second option. Also, for torch no extras are needed.

**Comment by macrosend-fukumoto** [comment]
@jkosek 
Thank you for helping me out again.
 I'll try it again with what you've told me.
 
 I'll close this as soon as I confirm the installation

**Comment by macrosend-fukumoto** [comment]
@jkosek 
I was able to install it, thank you!
