### ISSUE TITLE
Where can i export to triton with a warmup configuration?

### ISSUE THREAD

**Issue by msclock** [triton-inference-server/model_navigator#23]
Hello, thanks for your awesome triton automatic generator.When i export model to the configuration for tritonserver, some models need more time to initialize. Are there some codes to configure a simple warmup step automatically? Such as:
```txt
name: "yolov5"
max_batch_size: 2
input {
  name: "input__0"
  data_type: TYPE_FP32
  dims: 3
  dims: 1280
  dims: 1280
}
output {
  name: "output__0"
  data_type: TYPE_FP32
  dims: 100800
  dims: 85
}
instance_group {
  kind: KIND_GPU
}
dynamic_batching {
}
backend: "pytorch"
model_warmup [ # a warmup config field
    {
        name: "warmup_requests"
        batch_size: 1
        inputs: {
            key: "input__0" # input key
            value: {
                random_data: true
                dims: [3 ,1280, 1280] # random data
                data_type: TYPE_FP32
            }
        }
    }
]
```
The above model_warmup config will enable tritonserver to execute a warmup step when it launch a model. And if the warmup failed, then the model failed launching.

**Comment by jkosek** [comment]
@msclock at the moment we do not support this field, but we will add this to our roadmap. Let me update this issue once we would have an ETA for it.

**Comment by msclock** [comment]
@jkosek  Thanks for your reply and  expect this feature to be on the ETA.

**Comment by jkosek** [comment]
@msclock are we good to close the issue?

**Comment by msclock** [comment]
> @msclock are we good to close the issue?

@jkosek Thank you so much for implementing the warmup feature. I've used it and will never use additional scripts to supplement the warmup configuration again.
