### ISSUE TITLE
looks like a bug while in utils.dataloader.load_samples

### ISSUE THREAD

**Issue by supdizh** [triton-inference-server/model_navigator#27]
**Version**:0.74
**Detailed steps to reproduce the bug**: after nav.optimize, check samples(*.npz) consistency in `model_input` and `model_output` with the same index

**problems**:
https://github.com/triton-inference-server/model_navigator/blob/8baf51016810cada8a750887758eabd5d1e6910d/model_navigator/utils/dataloader.py#L194C1-L194C5
 `sorted(samples_dirpath.iterdir())` 
Whiling loading  samples(*.npz) from files, this line will result in un-expected loading sequence as 
0.npz, 1.npz, 10.npz, 100.npz, 2.npz ....
rather than expected index ascending way 

And with this un-expected loading sequence, npz's in `model_output` directory will not match thoese in `model_input` directory, causing failure in correctness/verifymodel

**maybe change this line to someting like**:
`sorted(samples_dirpath.iterdir(), key=lambda f: int(''.join(filter(str.isdigit, str(f)))))`
or use some regex to extract the index

**Comment by jkosek** [comment]
Thanks @supdizh. We are aware of the issue and plan to fix it in upcoming release.

**Comment by jkosek** [comment]
This was fixed in 0.7.3 release: https://github.com/triton-inference-server/model_navigator/releases/tag/v0.7.3
