### ISSUE TITLE
PyTreeMetaData infered wrong input mapping, causing wrong nav.optimize

### ISSUE THREAD

**Issue by supdizh** [triton-inference-server/model_navigator#28]
maybe we need a more fool-proof PyTreeMetaData?

**Version**:0.7.4
**Detailed steps to reproduce the bug**: 
    1. use the torch bert example in code repo
    2. change related codes from stuffs of `DistilBertForMaskedLM` to `BertModel` instead, which accept 3 inputs(input_ids, attention_mask, token_type_ids) instead of 2
    3. run optimize.py and check the generated {model}/reproduce_***.sh, you'll see a wrong metadata input arg as:
    `"pytree_metadata": {"metadata": {"input_ids": "input_ids", "token_type_ids": "attention_mask", "attention_mask": "token_type_ids"}, "tensor_type": "torch"}}'`
    PyTreeMetadata Inferrred a wrong mapping for "token_type_ids"/"attention_mask", thus making subsequent conversion/evaluation wrong

**possible cause?:**
https://github.com/triton-inference-server/model_navigator/blob/8baf51016810cada8a750887758eabd5d1e6910d/model_navigator/core/tensor.py#L370C1-L370C1

PyTreeMetaData now inferred input mapping from samples(which is a dict for this case, {'input_id': ..., 'token_type_ids':..., 'attention_mask':...), and it relied on the **order of the keys SAME TO those required in BertModel**, which is actually (['input_id', 'attention_mask', 'token_type_ids']), 
maybe use the dict keys' name aswell, to infer metadata?

**Comment by jkosek** [comment]
Thanks @supdizh. We will take a look at this.

**Comment by jkosek** [comment]
@supdizh could you let us know if the issue has been fixed with the latest version?
