### ISSUE TITLE
Change triton version to be used for the model navigator

### ISSUE THREAD

**Issue by Aun0124** [triton-inference-server/model_navigator#3]
I saw that this model_navigator uses triton version 21.05
If I want to use the version of 21.02 , how can I config it as I have errors on different version of tensorrt and i think is because different triton version?

**Comment by jkosek** [comment]
Have you checked `container_version` in YAML or `--container-version` CLI option? You can provide the desired version using that argument. Conversions and evaluation would goes on the same version of containers.

If you provide different version of container than default you would also need to use `triton_launch_mode=docker` or `--triton-launch-mode docker`.

**Comment by jkosek** [comment]
@TANKIANAUN did that help solve the problem?
