### ISSUE TITLE
Add support to override default model.py file name

### ISSUE THREAD

**Issue by shixianc** [triton-inference-server/model_navigator#32]
TritonServer allows user to override model.py default file name for python backends (this request can also apply to other backends). https://docs.nvidia.com/deeplearning/triton-inference-server/user-guide/docs/user_guide/model_repository.html#python-models

However nav does not support this field in ModelConfig when calling add_model(). Also when we pass a file called "xxx.py" it still overwrites the file name using the line https://github.com/triton-inference-server/model_navigator/blob/72ded98d2322bd0c0fd4e6b8ab718a8502306295/model_navigator/triton/model_repository.py#L444.

Feature Request: Support this new field on ModelConfig, and use the user provided filename directly (xxx.py) when deploying model, if the new field is provided.

**Comment by jkosek** [comment]
Hi @shixianc. The option is going to be provide in next release. Thanks for adding the feature request.

**Comment by jkosek** [comment]
The option has been added in 0.7.5 version.
