### ISSUE TITLE
When inferring with PyTritonAdapter, the results are different.

### ISSUE THREAD

**Issue by caffeinism** [triton-inference-server/model_navigator#35]
```
import model_navigator as nav
package = nav.package.load("package.nav")
pytriton_adapter = nav.pytriton.PyTritonAdapter(
    package=package, strategy=nav.MaxThroughputStrategy()
) # OnnxCUDARuntime is applied.
model_runner = pytriton_adapter.runner
model_runner.activate()

ort_sess = ort.InferenceSession("navigator_workspace/onnx/model.onnx")

output1 = ort_sess.run(None, {
    "input_values": data[0].numpy(),
})
output2 = model_runner.infer({
    "input_values": data[0].numpy()
})
```

`output1` and `output2` are sharply different. Even though the graph is in the navigator workspace.

**Comment by jkosek** [comment]
Hi @caffeinism. Could you share the providers configured for session?
```
ort_sess = ort.InferenceSession("navigator_workspace/onnx/model.onnx")
``` 
Based on documentation you need to specify the execution provider explicitly since ONNXRuntime 1.10. Otherwise the CPU is used by default: https://onnxruntime.ai/docs/api/python/api_summary.html#load-and-run-a-model

**Comment by caffeinism** [comment]
Aha I was ignorant about ONNX. After rerunning, the difference with ONNX seems to be less than 1%.
