### ISSUE TITLE
Segfault Immediately After Hifigan Conversion from TorchScript

### ISSUE THREAD

**Issue by okdimok** [triton-inference-server/model_navigator#7]
## Steps to reproduce

1. Get a hifigan model from NeMo and export it to .pt

```bash
docker run --rm --gpus '"device=0"' -it --ipc=host \
-v $HOME/:/ext_home \
-v ${PWD}:${PWD} \
 -w ${PWD} \
--name $USER_nemo \
nvcr.io/nvidia/nemo:1.3.0
```

In the container above, run the following python code:
```python
from nemo.collections.tts.models import HifiGanModel

model = HifiGanModel.from_pretrained(model_name="tts_hifigan")
model.export("./hifigan.pt")
```

2. Run model-navigator container
```bash
git clone https://github.com/triton-inference-server/model_navigator.git
# Optional
# git checkout v0.2.2
make docker
cd ..

docker run -it --rm \
 --gpus 1 \
 -v /var/run/docker.sock:/var/run/docker.sock \
 -v ${PWD}:${PWD} \
 -w ${PWD} \
 --net host \
 --name model-navigator \
 model-navigator /bin/bash
```

3. Get my Model Navigator config from [Google Drive](https://drive.google.com/file/d/1h1bwv8_Fh-3ReO8nZh7QzjS8mKZESLn6/view?usp=sharing)

3. Run model-navigator inside the container:
```
cp navigator_config.yaml navigator_config_run.yaml; model-navigator run --config-path navigator_config_run.yaml
```

## An Error

It results in a [log](https://drive.google.com/file/d/1kSK76FJZyRza8AbDz_xNL0Nt5rlsgYAS/view?usp=sharing) that ends like
```bash
[34m2021-10-20 15:57:10[0m - [1;34mWARNING[0m - [34mpolygraphy.transformers:[0m [33mThis conversion should be done on target GPU platform[0m
[34m2021-10-20 15:58:05[0m - [1;34mINFO[0m - [34mpolygraphy.transformers:[0m Polygraphy onnx2trt succeed.
[0m
Segmentation fault (core dumped)    
```

I've reconstruncted a backtrace of the segfault, and [here it is in the textual form](https://drive.google.com/file/d/18Xn5S1pDWds87m5iu5lHLxRcrfFgjizr/view?usp=sharing).
The coredump itself is too large to share.

Seems, like there is some error in protobuf description of ONNX-ML. Maybe the onnx version used is unstable.

## Environment
 NVIDIA-SMI 470.57.02    Driver Version: 470.57.02    CUDA Version: 11.4 
 Tesla V100-PCIE-16GB
Using Linux 4.18.0-305.17.1.el8_4.x86_64 #1 SMP x86_64 x86_64 x86_64 GNU/Linux  
CentOS Linux release 8.4.2105
Tested at v0.2.2, commit 988e96d0fd77f0c43699685bd0d287c5a0f5052d

**Comment by jkosek** [comment]
@okdimok I have checked the model on Ubuntu 20.04 and 0.2.2 version of Navigator. The process was handing at the conversion step.

On 0.2.3 the conversion passed and profiling was done without a problem. Could you try the latest release 0.2.3? It uses 21.09 containers by default.

Please, extend also your config with missing dtypes information for input:
```
dtypes:
  INPUT__0: float32
```

This will assure the profiling data will be created correctly.

**Comment by jkosek** [comment]
@okdimok is the problem still appearing?
