### ISSUE TITLE
[feature] add support for creating ensemble model config

### ISSUE THREAD

**Issue by Rusteam** [triton-inference-server/model_navigator#9]
Would you consider letting users add ensemble configs using `model-navigator triton-config-model`?

**Comment by jkosek** [comment]
@Rusteam we have this in long term plans but not ETA for that now.

**Comment by Rusteam** [comment]
Maybe I can help?

**Comment by jkosek** [comment]
We are currently preparing new release which brings some new features and change the current workflow which would impact the potential ensembles design.

What we could start now is design how the automatic configuration for ensembles could work. We would appreciate the ideas and use cases that users might have to bring some more context and find the right approach.

**Comment by Rusteam** [comment]
It's hard to come up with something other than simply creating a yaml config and then converting it to pbtxt.

**Comment by jkosek** [comment]
@rnddvsrt sorry for the delayed response. Things have been quiet here lately, but I hope to share more updates with you soon.
